**T_Test**

In [ ]:
import math
dict1={'SASTRA':150,'UNIVERSITY':200,'THANJAVUR':700,'INDIA':900,'SASTRA UNIVERSITY':175,'THANJAVUR INDIA':250,'UNIVERSITY THANJAVUR':4}
word=input("Enter the Bigram: ").upper()
word_list=word.split(' ') #length of wordlist will be 2 since word is a bi-gram
n=100000      #total no of words
try:
  x_bar=dict1[word]/n    
  mu=(dict1[word_list[0]]*dict1[word_list[1]])/n**2
  t_value=(x_bar-mu)/math.sqrt(x_bar/n)
  print(f"T-Test value: {t_value}")
  if t_value<2.576: #for confidence value of 0.05
    print("Accept Null Hypothesis\n")
    print("The words do not form a collocation")
  else:
    print("Reject null hypothesis")
    print(f'The words {word_list[0]} {word_list[1]} forms a collocation')
except Exception:
  if len(word_list)!=2:
    print("Entered word is not a Bigram")
  else:
    print("Please enter a correct Bigram")



**CHI_SQUARE TEST**




In [ ]:
import numpy as np
obs_arr=np.array([[8,4667],[15820,14287181]])
print("Observed Array: ")
print(obs_arr)
new_count=obs_arr[0,0]+obs_arr[1,0]
notnew_count=obs_arr[0,1]+obs_arr[1,1]
company_count=obs_arr[0,0]+obs_arr[0,1]
notcompany_count=obs_arr[1,0]+obs_arr[1,1]
N=obs_arr[0,0]+obs_arr[0,1]+obs_arr[1,0]+obs_arr[1,1]
print('Total count: ',N)#here N is total num of words
exp11=(new_count)/N*(company_count)
exp12=(notnew_count)/N*(company_count)
exp21=(new_count)/N*(notcompany_count)
exp22=(notnew_count)/N*(notcompany_count)
exp_arr=np.array([[exp11,exp12],[exp21,exp22]])
chi_square_arr=(obs_arr-exp_arr)**2/exp_arr
chi_square=np.sum(chi_square_arr)
print("Expected Array:")
print(exp_arr)
print("Chi-Test Array:")
print(chi_square_arr)
print(f'Chi-Test value: {chi_square}')
if chi_square<6.314:
  print('Accept null hypothesis')
  print('The words new companies do not form a collocation')
else:
  print('Reject null hypothesis')
  print('The words new companies  form a collocation')


Observed Array: 
[[       8     4667]
 [   15820 14287181]]
Total count:  14307676
Expected Array:
[[5.17176235e+00 4.66982824e+03]
 [1.58228282e+04 1.42871782e+07]]
Chi-Test Array:
[[1.54665425e+00 1.71289560e-03]
 [5.05530876e-04 5.59867605e-07]]
Chi-Test value: 1.5488732388236603
Accept null hypothesis
The words new companies do not form a collocation
